// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Graphs")>]
[<assembly: AssemblyProductAttribute("AlgorithmPad")>]
[<assembly: AssemblyDescriptionAttribute("Algorithms Scratchpad")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Graphs"
    let [<Literal>] AssemblyProduct = "AlgorithmPad"
    let [<Literal>] AssemblyDescription = "Algorithms Scratchpad"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
